version: '3'
services:
 web:
  image: "zapposapi"
  environment:
    - DBHOST=db
    - DBPORT=3306
    - CACHEHOST=cache
    - CACHEPORT=6379
  ports:
   - "80:8080"
  depends_on:
   - "db"
  command: [server]
 db:
    image: "zapposdb"
 cache:
    image: "redis"
